### ISSUE TITLE
Better handling if data is not existent in Oura cloud

### ISSUE THREAD

**Issue by leikoilja** [nitobuendia/oura-custom-component#9]
Hey, thanks for the integration, great stuff 🔥 

So, I just got Oura ring and setup the integration getting a few console errors like so:
![image](https://user-images.githubusercontent.com/10655107/144744866-b5ed1ea6-ed49-4d0c-8c24-9f0b94be92ef.png)

And the error message is fair enough, the could indeed has no historical data yet, it only has data for the past 2 days.

Suggestion: instead of `error` log entires, log it as `warning` or even `debug` saying "no data found for X day, skipping..." or smth like that :)

**Comment by nitobuendia** [comment]
Hi @leikoilja - thanks for using it and the feedback.

I think both are good feedack. Warning seems more appropriate as it may or may not be an issue. One of the messages is already info, but I think they could be combined into one with some change in logic. I also like the idea of changing to "No data found for" instead of "Unable to read".

Let me test and send a quick change.

**Comment by nitobuendia** [comment]
![Screenshot 2021-12-06 at 18 43 07](https://user-images.githubusercontent.com/16522489/144832426-43fd7e76-13a8-481c-9a09-469714d50483.png)

This is how the new warnings will be shown. It also seems that the system is groupping them.
